const dishList = [
  {
    id: 1,
    title: "Pink chumchum",
    path: "/images/pinkchumchum.jpg",
    rating: 5,
    category: "Sweets",
  },
  {
    id: 2,
    title: "Barfi",
    path: "/images/barfisweet.jpg",
    rating: 4,
    category: "Sweets",
  },
  {
    id: 3,
    title: "Samosa",
    path: "/images/samosa.jpg",
    rating: 4,
    category: "Veg",
  },
  {
    id: 4,
    title: "Matthi",
    path: "/images/matthi.jpg",
    rating: 5,
    category: "Sweets",
  },
  {
    id: 5,
    title: "GulGule",
    path: "/images/gulgule.jpg",
    rating: 4,
    category: "Sweets",
  },
  {
    id: 6,
    title: "Egg Curry",
    path: "/images/eggcurry.jpg",
    rating: 4,
    category: "Non Veg",
  },
  {
    id: 7,
    title: "Shakkar Paarey",
    path: "/images/shakkarpaarey.jpg",
    rating: 5,
    category: "Sweets",
  },
  {
    id: 8,
    title: "gulaab jamoon",
    path: "/images/gulaabjamoon.jpg",
    rating: 4,
    category: "Sweets",
  },
  {
    id: 9,
    title: "white rasgulla",
    path: "/images/whiterasgulla.jpg",
    rating: 5,
    category: "Sweets",
  },
  {
    id: 10,
    title: "Chicken Chilli",
    path: "/images/chickenchilli.jpg",
    rating: 5,
    category: "Non Veg",
  },
  {
    id: 11,
    title: "Paneer Chilli",
    path: "/images/paneerchilli.jpg",
    rating: 5,
    category: "Veg",
  },
  {
    id: 12,
    title: "Daal Makhni",
    path: "/images/daalmakhni.jpg",
    rating: 4,
    category: "Veg",
  },
  {
    id: 13,
    title: "Shahi Paneer",
    path: "/images/shahipaneer.jpg",
    rating: 5,
    category: "Veg",
  },
  {
    id: 14,
    title: "butter chicken",
    path: "/images/butterchicken.jpg",
    rating: 4,
    category: "Non Veg",
  },
  {
    id: 15,
    title: "noodles",
    path: "/images/noodles.jpg",
    rating: 4,
    category: "Veg",
  },
  {
    id: 16,
    title: "rice",
    path: "/images/rice.jpg",
    rating: 4,
    category: "Veg",
  },
  {
    id: 17,
    title: "ras malai",
    path: "/images/rasmalai.jpg",
    rating: 4,
    category: "Sweets",
  },
  {
    id: 18,
    title: "lassi",
    path: "/images/lassi.jpg",
    rating: 5,
    category: "Drinks",
  },
  {
    id: 19,
    title: "coffee",
    path: "/images/coffee.jpg",
    rating: 4,
    category: "Drinks",
  },
  {
    id: 20,
    title: "tea",
    path: "/images/tea.jpg",
    rating: 4,
    category: "Drinks",
  },
  {
    id: 21,
    title: "Chilli Fish",
    path: "/images/chillifish.jpg",
    rating: 5,
    category: "Non Veg",
  },
  
];

export default dishList;
